FROM ruby:<%= ruby_version %>-alpine

RUN apk add --no-cache --update \
ack \
bash \
build-base \
cloc \
curl \
git \
htop \
less \
libc6-compat \
libsass \
linux-headers \
nodejs \
npm \
postgresql-client \
postgresql-dev \
redis \
tzdata \
vim \
yarn

RUN gem install bundler

CMD tail -f /dev/null
